# Generated by Django 5.2.2 on 2025-06-07 13:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borrow',
            name='return_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 6, 21, 13, 19, 31, 9655, tzinfo=datetime.timezone.utc)),
        ),
    ]
