# Generated by Django 5.2.2 on 2025-06-08 08:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_borrow_return_date_alter_review_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='published_date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='borrow',
            name='borrow_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 6, 8, 8, 51, 43, 999959, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='borrow',
            name='return_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 6, 22, 8, 51, 43, 999967, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='reserve',
            name='revserve_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 6, 8, 8, 51, 43, 999594, tzinfo=datetime.timezone.utc)),
        ),
    ]
