# Generated by Django 5.2.2 on 2025-06-08 08:54

import datetime
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_book_published_date_alter_borrow_borrow_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borrow',
            name='borrow_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='borrow',
            name='return_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 6, 22, 8, 54, 2, 895451, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='reserve',
            name='revserve_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
