# Generated by Django 5.2.2 on 2025-06-10 12:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_borrow_borrow_date_alter_borrow_return_date_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reserve',
            old_name='revserve_date',
            new_name='reserve_date',
        ),
        migrations.AddField(
            model_name='reserve',
            name='reserve_expire_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 6, 24, 12, 6, 15, 20468, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='borrow',
            name='return_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 6, 24, 12, 6, 15, 20826, tzinfo=datetime.timezone.utc)),
        ),
    ]
