# Generated by Django 5.2.2 on 2025-06-10 12:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_rename_revserve_date_reserve_reserve_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reserve',
            name='reserve_expire_date',
        ),
        migrations.AlterField(
            model_name='borrow',
            name='return_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 6, 24, 12, 15, 36, 987255, tzinfo=datetime.timezone.utc)),
        ),
    ]
