# Generated by Django 5.2.2 on 2025-06-10 12:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_remove_reserve_reserve_expire_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='borrow',
            name='fine',
        ),
        migrations.AlterField(
            model_name='borrow',
            name='return_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 6, 24, 12, 20, 49, 6666, tzinfo=datetime.timezone.utc)),
        ),
        migrations.DeleteModel(
            name='Fine',
        ),
    ]
