# Generated by Django 5.2.2 on 2025-06-10 12:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_remove_borrow_fine_alter_borrow_return_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borrow',
            name='borrow_date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='borrow',
            name='return_date',
            field=models.DateField(default=datetime.date(2025, 6, 24)),
        ),
    ]
