# Generated by Django 5.2.2 on 2025-06-19 09:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_borrow_borrow_date_alter_borrow_return_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borrow',
            name='return_date',
            field=models.DateField(default=datetime.date(2025, 7, 3)),
        ),
        migrations.AlterField(
            model_name='reserve',
            name='status',
            field=models.CharField(choices=[('T', 'Taken'), ('A', 'Available')], default='A', max_length=1),
        ),
    ]
