# Generated by Django 5.2.2 on 2025-06-22 09:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_alter_borrow_return_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserve',
            name='reserve_date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
